[global]
pprof = ":6060"

# server
dc = "shenzhen"
name = "biz"
nid = "shenzhen_biz_1"
nip = "8.129.55.41"

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
# addrs = ["127.0.0.1:2379"]
addrs = ["8.129.55.41:2379"]

[signal]
#listen ip port
host = "0.0.0.0"
port = "8443"
# cert= "configs/cert.pem"
# key= "configs/key.pem"

[amqp]
# url = "amqp://guest:guest@localhost:5672/"
url = "amqp://zhouwq:123456@8.129.55.41:5672/admin"

