[global]
pprof = ":6063"

# server
dc = "shenzhen"
name = "dist"
nid = "shenzhen_dist_1"
nip = "127.0.0.1"

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["127.0.0.1:2379"]

[signal]
#listen ip port
host = "0.0.0.0"
port = "8444"
# cert= "configs/cert.pem"
# key= "configs/key.pem"

[nats]
url = "nats://127.0.0.1:4222"
