[global]
pprof = ":6063"

# server
dc = "shenzhen"
name = "dist"
nid = "shenzhen_dist_1"
nip = "127.0.0.1"

[log]
level = "info"
# level = "debug"

[etcd]
addrs = "127.0.0.1:2379"

[signal]
#listen ip port
host = "0.0.0.0"
port = "8444"
# cert= "configs/cert.pem"
# key= "configs/key.pem"

[nats]
url = "127.0.0.1:4222"
natslog = "127.0.0.1:4222"
[probe]
host="0.0.0.0"
port="7071"
