[global]
pprof = ":6061"

# server
dc = "shenzhen"
name = "islb"
nid = "shenzhen_islb_1"
nip = "127.0.0.1"

[log]
level = "info"

[etcd]
addrs = "127.0.0.1:2379"

[nats]
url = "127.0.0.1:4222"

[redis]
addrs = [":6379"]
password = ""
db = 0
tdb = 1
