[global]
pprof = ":6061"

# name
name = "islb"
serverid = shenzhen_islb_1

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
# addrs = ["127.0.0.1:2379"]
addrs = ["8.129.55.41:2379"]

[amqp]
# url = "amqp://guest:guest@localhost:5672/"
url = "amqp://zhouwq:123456@8.129.55.41:5672/admin"

[redis]
# addrs = [":6379"]
addrs = ["8.129.55.41:6379"]
password = ""
db = 0
