[global]
pprof = ":6064"

# server
dc = "shenzhen"
name = "issr"
nid = "shenzhen_issr_1"
nip = "127.0.0.1"

[log]
level = "info"
# level = "debug"

[etcd]
addrs = "127.0.0.1:2379"

[nats]
url = "127.0.0.1:4222"
natslog = "127.0.0.1:4222"
[kafka]
url = "127.0.0.1:9092"

[probe]
host="0.0.0.0"
port="7074"
